MIRROR_WEBCAM = True
MODEL_SIZE = "small"  # small / base / large
COLORMAP_NAME = "INFERNO"
MAX_IMAGE_SIDE = 512

print(f"MIRROR_WEBCAM={MIRROR_WEBCAM}, MODEL_SIZE={MODEL_SIZE}, COLORMAP={COLORMAP_NAME}")
